[mypy]
python_version = 3.12
strict = True
plugins = pydantic.mypy
exclude = tests/

[mypy-litellm.*]
ignore_missing_imports = True

[mypy-mcp.*]
ignore_missing_imports = True

[mypy-opentelemetry.instrumentation.*]
ignore_missing_imports = True

[mypy-sse_starlette.*]
ignore_missing_imports = True
